#!/bin/bash
var1=$(echo "scale=4; 3.44 / 5" | bc)
echo The answer is $var1
my_variable="Full"
if test $my_variable; then 
  echo "No expression returns a True"
else
  echo "No expression returns a False"
fi


value1=10
value2=11

if [ $value1 -gt 5 ] ; then
  echo "The test value $value1 is greater than 5"
fi

if [ $value1 -eq $value2 ] ; then
  echo "The values are equal"
else
  echo "The values are different"
fi

testuser=xjfang1
if [ $USER != $testuser ]; then
  echo "This is not $testuser"
else
  echo "Welcome $testuser"
fi
